name=[]
name.append("luxun")
name.append("zhou")
name.append("yuan")
name.append("mao")
print(name)
print(f"I want to invite you to come my home {name[0].title()}")
print("-"*50)
name.insert(1,"deng")
print(name[1].title())
a=name.pop(1)
del name[-1]
print(name)
name.remove("zhou")
print(name)
print("-"*50)
a=['a','b','c','d']
print(a)
a.sort(reverse=True)
print(a)
a.reverse()
print(a)
print(len(a))
print(len(name))
